function DataArrayAll=readCleanSurveyData(CleanDataFileName)

    % read the file containing the cleaned survey data
    fid = fopen(CleanDataFileName, 'r');
    DataArrayAllHelper= textscan(fid,'%s %f %f %f %f %f %f %f %s %f %f %f %f', 'headerlines', 1, 'delimiter', ',');
    DataArrayAll=[DataArrayAllHelper{1}...
        num2cell(DataArrayAllHelper{2})...
        num2cell(DataArrayAllHelper{3})...
        num2cell(DataArrayAllHelper{4})...
        num2cell(DataArrayAllHelper{5})...
        num2cell(DataArrayAllHelper{6})...
        num2cell(DataArrayAllHelper{7})...
        num2cell(DataArrayAllHelper{8})...
        DataArrayAllHelper{9}...
        num2cell(DataArrayAllHelper{10})...
        num2cell(DataArrayAllHelper{11})...
        num2cell(DataArrayAllHelper{12})...
        num2cell(DataArrayAllHelper{13})];
    fclose(fid);

end

